version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - face_data:/app/data
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/facedb
      - PYTHONPATH=/app
    depends_on:
      - db
    command: bash -c "python scripts/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=facedb

  redis:
    image: redis:6-alpine

volumes:
  postgres_data:
  face_data:
